// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,
  currentUser,
} from "@clerk/nextjs";
import { SWRConfig } from 'swr';
import "./globals.css";
import { SWRProvider } from "./swr-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <SWRProvider>
        <html lang="en">
          <body className={inter.className}>
            <div id="modal-area"></div>
            <div>
              <ClerkLoading>
                <div className="flex flex-col items-center text-center mt-32">
                  LOADING...
                </div>
              </ClerkLoading>
              <ClerkLoaded>
                {children}
              </ClerkLoaded>
            </div>
          </body>
        </html>
      </SWRProvider>
    </ClerkProvider>
  );
}
