import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";


import phoneIcon from "@/components/Icons/phoneIcon";
import ContentContainer from "@/components/ContentContainer";
import listIcon from "@/components/Icons/listIcon";
import starIcon from "@/components/Icons/starIcon";
import trendUpIcon from "@/components/Icons/trendUpIcon";
import locationIcon from "@/components/Icons/locationIcon";
import SideMenu from "@/components/SideMenu";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideMenu />
        <div id="app-modal"></div>
        <div> test</div>
      </body>
    </html>
  );
}
